# Generated by Django 4.0.6 on 2022-08-16 01:15

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_set_wd_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wikidot_username',
            field=models.TextField(db_collation = "case_insensitive", max_length=150, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Имя пользователя на Wikidot'),
        ),
    ]
